### ISSUE TITLE
Pipeline execution leads to transformation exception

### ISSUE THREAD

**Issue by mathiaszinnen** [jvalue/ods#177]
Executing the example pipeline from the ui does not work. The transformation service logs show the following exception:

``` 
Possibly Unhandled Rejection at: Promise Promise {
transformation_1 | <rejected> TypeError: given data is no object or array
transformation_1 | at VM2SandboxExecutor.assertIsObjectOrArray (/app/dist/pipeline-execution/sandbox/vm2SandboxExecutor.js:14:19)
transformation_1 | at VM2SandboxExecutor.execute (/app/dist/pipeline-execution/sandbox/vm2SandboxExecutor.js:18:14)
transformation_1 | at /app/dist/pipeline-execution/pipelineExecutor.js:20:79
transformation_1 | at PipelineExecutor.executionTimeInMillis (/app/dist/pipeline-execution/pipelineExecutor.js:13:24)
transformation_1 | at PipelineExecutor.executeJob (/app/dist/pipeline-execution/pipelineExecutor.js:20:37)
transformation_1 | at PipelineConfigManager.triggerConfig (/app/dist/pipeline-config/pipelineConfigManager.js:59:50)
transformation_1 | at processTicksAndRejections (internal/process/task_queues.js:97:5)
transformation_1 | at async PipelineConfigConsumer.consumeEvent (/app/dist/api/amqp/pipelineConfigConsumer.js:36:21)
transformation_1 | } reason: TypeError: given data is no object or array
transformation_1 | at VM2SandboxExecutor.assertIsObjectOrArray (/app/dist/pipeline-execution/sandbox/vm2SandboxExecutor.js:14:19)
transformation_1 | at VM2SandboxExecutor.execute (/app/dist/pipeline-execution/sandbox/vm2SandboxExecutor.js:18:14)
transformation_1 | at /app/dist/pipeline-execution/pipelineExecutor.js:20:79
transformation_1 | at PipelineExecutor.executionTimeInMillis (/app/dist/pipeline-execution/pipelineExecutor.js:13:24)
transformation_1 | at PipelineExecutor.executeJob (/app/dist/pipeline-execution/pipelineExecutor.js:20:37)
transformation_1 | at PipelineConfigManager.triggerConfig (/app/dist/pipeline-config/pipelineConfigManager.js:59:50)
transformation_1 | at processTicksAndRejections (internal/process/task_queues.js:97:5)
transformation_1 | at async PipelineConfigConsumer.consumeEvent (/app/dist/api/amqp/pipelineConfigConsumer.js:36:21)
```

**Comment by mathiaszinnen** [comment]
closed by #178
